/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KhFi6cO8qUA
 */

//import next stuff
import Link from "next/link";

//import shadcnui stuff
import { Separator } from "@/components/ui/separator";

export function Footer() {
  return (
    <footer className="w-full mt-40 py-6 md:py-12 border-t bg-gray-50 dark:bg-gray-950">
      <div className="max-w-6xl mx-auto px-4 md:px-6">
        <div className="container gap-6">
          <div className="space-y-2 mb-10">
            <h4 className="text-2xl font-semibold text-primary">
              <Link href="/">Fullstack</Link>
            </h4>
            <p className="text-muted-foreground">
              Insert your snappy one liner here.
            </p>
          </div>
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">
            <div className="space-y-2">
              <h4 className="text-lg text-muted-foreground">Company</h4>
              <ul className="flex flex-col gap-2 ">
                <li>
                  <Link href="#">About Us</Link>
                </li>
                <li>
                  <Link href="#">Blog</Link>
                </li>
              </ul>
            </div>
            <div className="space-y-2">
              <h4 className="text-lg  text-muted-foreground">Product</h4>
              <ul className="flex flex-col gap-2">
                <li>
                  <Link href="#">Compare Us</Link>
                </li>
                <li>
                  <Link href="#">Case Studies</Link>
                </li>
              </ul>
            </div>
            <div className="space-y-2">
              <h4 className="text-lg  text-muted-foreground">Solutions</h4>
              <ul className="flex flex-col gap-2">
                <li>
                  <Link href="#">For Sales Teams</Link>
                </li>
                <li>
                  <Link href="#">For Product Teams</Link>
                </li>
                <li>
                  <Link href="#">For Marketing Teams</Link>
                </li>
                <li>
                  <Link href="#">For Operations Teams</Link>
                </li>
                <li>
                  <Link href="#">For Legal Teams</Link>
                </li>
              </ul>
            </div>
            <div className="space-y-2">
              <h4 className="text-lg  text-muted-foreground">Resources</h4>
              <ul className="flex flex-col gap-2">
                <li>
                  <Link href="#">Help Center</Link>
                </li>
                <li>
                  <Link href="#">Community</Link>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}
