/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KhFi6cO8qUA
 */

//import shadcnui stuff
import { Separator } from "@/components/ui/separator";

export function Footer() {
  return (
    <footer className="w-full py-6 md:py-12 border-t bg-gray-50 dark:bg-gray-950">
      <div className="container gap-6 px-4 md:px-6">
        <div className="space-y-2 mb-10">
          <h4 className="text-2xl font-semibold text-primary">Fullstack</h4>
          <p className=" text-muted-foreground">
            Insert your snappy one liner here.
          </p>
        </div>
        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">
          <div className="space-y-2">
            <h4 className="text-lg text-muted-foreground">Company</h4>
            <ul className="flex flex-col gap-2 ">
              <li>About Us</li>
              <li>Blog</li>
            </ul>
          </div>
          <div className="space-y-2">
            <h4 className="text-lg  text-muted-foreground">Product</h4>
            <ul className="flex flex-col gap-2">
              <li>Compare Us</li>
              <li>Case Studies</li>
            </ul>
          </div>
          <div className="space-y-2">
            <h4 className="text-lg  text-muted-foreground">Solutions</h4>
            <ul className="flex flex-col gap-2">
              <li>For Sales Teams</li>
              <li>For Product Teams</li>
              <li>For Marketing Teams</li>
              <li>For Operations Teams</li>
              <li>For Legal Teams</li>
            </ul>
          </div>
          <div className="space-y-2">
            <h4 className="text-lg  text-muted-foreground">Resources</h4>
            <ul className="flex flex-col gap-2">
              <li>Help Center</li>
              <li>Community</li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  );
}
